/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AgentState {
  'newsAgent' : AgentStatus,
  'lastEventCount' : bigint,
  'lastRunAt' : bigint,
  'mapAgent' : AgentStatus,
  'videoAgent' : AgentStatus,
}
export type AgentStatus = { 'idle' : null } |
  { 'error' : null } |
  { 'complete' : null } |
  { 'running' : null };
export interface AnalyticsSnapshot {
  'locationsTracked' : bigint,
  'videosGenerated' : bigint,
  'tier' : string,
  'alertsDismissed' : bigint,
  'eventsToday' : bigint,
  'apiCallsThisHour' : bigint,
}
export interface ChatMessage {
  'id' : MessageId,
  'content' : string,
  'role' : Role,
  'timestamp' : Timestamp,
}
export interface HttpResponse {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<{ 'value' : string, 'name' : string }>,
}
export type MessageId = bigint;
export interface NewsArticle {
  'url' : string,
  'title' : string,
  'publishedAt' : string,
  'description' : string,
  'image' : string,
  'hasVideo' : boolean,
}
export interface NewsEvent {
  'id' : string,
  'lat' : number,
  'lng' : number,
  'url' : string,
  'title' : string,
  'country' : string,
  'source' : string,
  'publishedAt' : bigint,
  'description' : string,
  'severity' : string,
  'dismissed' : boolean,
}
export type Role = { 'user' : null } |
  { 'assistant' : null };
export interface SearchResult {
  'url' : string,
  'title' : string,
  'snippet' : string,
}
export interface SystemInfo {
  'status' : string,
  'llmStatus' : string,
  'uptimePlaceholder' : string,
  'messageCount' : bigint,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'checkQuota' : ActorMethod<
    [],
    { 'allowed' : boolean, 'limit' : bigint, 'remaining' : bigint }
  >,
  'clearChat' : ActorMethod<[], undefined>,
  'dismissEvent' : ActorMethod<[string], boolean>,
  'fetchNews' : ActorMethod<[], Array<NewsArticle>>,
  'getActiveAlerts' : ActorMethod<[], Array<NewsEvent>>,
  'getAgentState' : ActorMethod<[], AgentState>,
  'getAnalytics' : ActorMethod<[], AnalyticsSnapshot>,
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getEvents' : ActorMethod<[], Array<NewsEvent>>,
  'getGNewsKey' : ActorMethod<[], string>,
  'getLlmStatus' : ActorMethod<[], string>,
  'getNewsContextForChat' : ActorMethod<[], string>,
  'getOpenRouterKey' : ActorMethod<[], string>,
  'getRecentEvents' : ActorMethod<[bigint], Array<NewsEvent>>,
  'getSystemInfo' : ActorMethod<[], SystemInfo>,
  'getTier' : ActorMethod<[], string>,
  'incrementApiCall' : ActorMethod<[], undefined>,
  'incrementVideoCount' : ActorMethod<[], undefined>,
  'resetHourlyApiCalls' : ActorMethod<[], undefined>,
  'searchWeb' : ActorMethod<[string], Array<SearchResult>>,
  'sendMessage' : ActorMethod<[string], string>,
  'setGNewsKey' : ActorMethod<[string], undefined>,
  'setOpenRouterKey' : ActorMethod<[string], undefined>,
  'setTier' : ActorMethod<[string], boolean>,
  'storeEvent' : ActorMethod<[NewsEvent], undefined>,
  'transformHttpResponse' : ActorMethod<
    [{ 'context' : Uint8Array, 'response' : HttpResponse }],
    HttpResponse
  >,
  'triggerNewsRefresh' : ActorMethod<
    [],
    { 'success' : boolean, 'eventCount' : bigint }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];