/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NewsArticle = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'publishedAt' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Text,
  'hasVideo' : IDL.Bool,
});
export const NewsEvent = IDL.Record({
  'id' : IDL.Text,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'country' : IDL.Text,
  'source' : IDL.Text,
  'publishedAt' : IDL.Int,
  'description' : IDL.Text,
  'severity' : IDL.Text,
  'dismissed' : IDL.Bool,
});
export const AgentStatus = IDL.Variant({
  'idle' : IDL.Null,
  'error' : IDL.Null,
  'complete' : IDL.Null,
  'running' : IDL.Null,
});
export const AgentState = IDL.Record({
  'newsAgent' : AgentStatus,
  'lastEventCount' : IDL.Nat,
  'lastRunAt' : IDL.Int,
  'mapAgent' : AgentStatus,
  'videoAgent' : AgentStatus,
});
export const AnalyticsSnapshot = IDL.Record({
  'locationsTracked' : IDL.Nat,
  'videosGenerated' : IDL.Nat,
  'tier' : IDL.Text,
  'alertsDismissed' : IDL.Nat,
  'eventsToday' : IDL.Nat,
  'apiCallsThisHour' : IDL.Nat,
});
export const MessageId = IDL.Nat;
export const Role = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
export const Timestamp = IDL.Int;
export const ChatMessage = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'role' : Role,
  'timestamp' : Timestamp,
});
export const SystemInfo = IDL.Record({
  'status' : IDL.Text,
  'llmStatus' : IDL.Text,
  'uptimePlaceholder' : IDL.Text,
  'messageCount' : IDL.Nat,
});
export const SearchResult = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'snippet' : IDL.Text,
});
export const HttpResponse = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })),
});

export const idlService = IDL.Service({
  'checkQuota' : IDL.Func(
      [],
      [
        IDL.Record({
          'allowed' : IDL.Bool,
          'limit' : IDL.Nat,
          'remaining' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'clearChat' : IDL.Func([], [], []),
  'dismissEvent' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'fetchNews' : IDL.Func([], [IDL.Vec(NewsArticle)], []),
  'getActiveAlerts' : IDL.Func([], [IDL.Vec(NewsEvent)], ['query']),
  'getAgentState' : IDL.Func([], [AgentState], ['query']),
  'getAnalytics' : IDL.Func([], [AnalyticsSnapshot], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getEvents' : IDL.Func([], [IDL.Vec(NewsEvent)], ['query']),
  'getGNewsKey' : IDL.Func([], [IDL.Text], ['query']),
  'getLlmStatus' : IDL.Func([], [IDL.Text], ['query']),
  'getNewsContextForChat' : IDL.Func([], [IDL.Text], ['query']),
  'getOpenRouterKey' : IDL.Func([], [IDL.Text], ['query']),
  'getRecentEvents' : IDL.Func([IDL.Nat], [IDL.Vec(NewsEvent)], ['query']),
  'getSystemInfo' : IDL.Func([], [SystemInfo], ['query']),
  'getTier' : IDL.Func([], [IDL.Text], ['query']),
  'incrementApiCall' : IDL.Func([], [], []),
  'incrementVideoCount' : IDL.Func([], [], []),
  'resetHourlyApiCalls' : IDL.Func([], [], []),
  'searchWeb' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], []),
  'sendMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
  'setGNewsKey' : IDL.Func([IDL.Text], [], []),
  'setOpenRouterKey' : IDL.Func([IDL.Text], [], []),
  'setTier' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'storeEvent' : IDL.Func([NewsEvent], [], []),
  'transformHttpResponse' : IDL.Func(
      [
        IDL.Record({
          'context' : IDL.Vec(IDL.Nat8),
          'response' : HttpResponse,
        }),
      ],
      [HttpResponse],
      ['query'],
    ),
  'triggerNewsRefresh' : IDL.Func(
      [],
      [IDL.Record({ 'success' : IDL.Bool, 'eventCount' : IDL.Nat })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NewsArticle = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'publishedAt' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Text,
    'hasVideo' : IDL.Bool,
  });
  const NewsEvent = IDL.Record({
    'id' : IDL.Text,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'country' : IDL.Text,
    'source' : IDL.Text,
    'publishedAt' : IDL.Int,
    'description' : IDL.Text,
    'severity' : IDL.Text,
    'dismissed' : IDL.Bool,
  });
  const AgentStatus = IDL.Variant({
    'idle' : IDL.Null,
    'error' : IDL.Null,
    'complete' : IDL.Null,
    'running' : IDL.Null,
  });
  const AgentState = IDL.Record({
    'newsAgent' : AgentStatus,
    'lastEventCount' : IDL.Nat,
    'lastRunAt' : IDL.Int,
    'mapAgent' : AgentStatus,
    'videoAgent' : AgentStatus,
  });
  const AnalyticsSnapshot = IDL.Record({
    'locationsTracked' : IDL.Nat,
    'videosGenerated' : IDL.Nat,
    'tier' : IDL.Text,
    'alertsDismissed' : IDL.Nat,
    'eventsToday' : IDL.Nat,
    'apiCallsThisHour' : IDL.Nat,
  });
  const MessageId = IDL.Nat;
  const Role = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
  const Timestamp = IDL.Int;
  const ChatMessage = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'role' : Role,
    'timestamp' : Timestamp,
  });
  const SystemInfo = IDL.Record({
    'status' : IDL.Text,
    'llmStatus' : IDL.Text,
    'uptimePlaceholder' : IDL.Text,
    'messageCount' : IDL.Nat,
  });
  const SearchResult = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'snippet' : IDL.Text,
  });
  const HttpResponse = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text })),
  });
  
  return IDL.Service({
    'checkQuota' : IDL.Func(
        [],
        [
          IDL.Record({
            'allowed' : IDL.Bool,
            'limit' : IDL.Nat,
            'remaining' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'clearChat' : IDL.Func([], [], []),
    'dismissEvent' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'fetchNews' : IDL.Func([], [IDL.Vec(NewsArticle)], []),
    'getActiveAlerts' : IDL.Func([], [IDL.Vec(NewsEvent)], ['query']),
    'getAgentState' : IDL.Func([], [AgentState], ['query']),
    'getAnalytics' : IDL.Func([], [AnalyticsSnapshot], ['query']),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getEvents' : IDL.Func([], [IDL.Vec(NewsEvent)], ['query']),
    'getGNewsKey' : IDL.Func([], [IDL.Text], ['query']),
    'getLlmStatus' : IDL.Func([], [IDL.Text], ['query']),
    'getNewsContextForChat' : IDL.Func([], [IDL.Text], ['query']),
    'getOpenRouterKey' : IDL.Func([], [IDL.Text], ['query']),
    'getRecentEvents' : IDL.Func([IDL.Nat], [IDL.Vec(NewsEvent)], ['query']),
    'getSystemInfo' : IDL.Func([], [SystemInfo], ['query']),
    'getTier' : IDL.Func([], [IDL.Text], ['query']),
    'incrementApiCall' : IDL.Func([], [], []),
    'incrementVideoCount' : IDL.Func([], [], []),
    'resetHourlyApiCalls' : IDL.Func([], [], []),
    'searchWeb' : IDL.Func([IDL.Text], [IDL.Vec(SearchResult)], []),
    'sendMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
    'setGNewsKey' : IDL.Func([IDL.Text], [], []),
    'setOpenRouterKey' : IDL.Func([IDL.Text], [], []),
    'setTier' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'storeEvent' : IDL.Func([NewsEvent], [], []),
    'transformHttpResponse' : IDL.Func(
        [
          IDL.Record({
            'context' : IDL.Vec(IDL.Nat8),
            'response' : HttpResponse,
          }),
        ],
        [HttpResponse],
        ['query'],
      ),
    'triggerNewsRefresh' : IDL.Func(
        [],
        [IDL.Record({ 'success' : IDL.Bool, 'eventCount' : IDL.Nat })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };