/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SearchResult {
    url: string;
    title: string;
    snippet: string;
}
export type Timestamp = bigint;
export interface AnalyticsSnapshot {
    locationsTracked: bigint;
    videosGenerated: bigint;
    tier: string;
    alertsDismissed: bigint;
    eventsToday: bigint;
    apiCallsThisHour: bigint;
}
export interface NewsEvent {
    id: string;
    lat: number;
    lng: number;
    url: string;
    title: string;
    country: string;
    source: string;
    publishedAt: bigint;
    description: string;
    severity: string;
    dismissed: boolean;
}
export type MessageId = bigint;
export interface HttpResponse {
    status: bigint;
    body: Uint8Array;
    headers: Array<{
        value: string;
        name: string;
    }>;
}
export interface NewsArticle {
    url: string;
    title: string;
    publishedAt: string;
    description: string;
    image: string;
    hasVideo: boolean;
}
export interface ChatMessage {
    id: MessageId;
    content: string;
    role: Role;
    timestamp: Timestamp;
}
export interface AgentState {
    newsAgent: AgentStatus;
    lastEventCount: bigint;
    lastRunAt: bigint;
    mapAgent: AgentStatus;
    videoAgent: AgentStatus;
}
export interface SystemInfo {
    status: string;
    llmStatus: string;
    uptimePlaceholder: string;
    messageCount: bigint;
}
export enum AgentStatus {
    idle = "idle",
    error = "error",
    complete = "complete",
    running = "running"
}
export enum Role {
    user = "user",
    assistant = "assistant"
}
export interface backendInterface {
    checkQuota(): Promise<{
        allowed: boolean;
        limit: bigint;
        remaining: bigint;
    }>;
    clearChat(): Promise<void>;
    dismissEvent(id: string): Promise<boolean>;
    fetchNews(): Promise<Array<NewsArticle>>;
    getActiveAlerts(): Promise<Array<NewsEvent>>;
    getAgentState(): Promise<AgentState>;
    getAnalytics(): Promise<AnalyticsSnapshot>;
    getChatHistory(): Promise<Array<ChatMessage>>;
    getEvents(): Promise<Array<NewsEvent>>;
    getGNewsKey(): Promise<string>;
    getLlmStatus(): Promise<string>;
    getNewsContextForChat(): Promise<string>;
    getOpenRouterKey(): Promise<string>;
    getRecentEvents(limit: bigint): Promise<Array<NewsEvent>>;
    getSystemInfo(): Promise<SystemInfo>;
    getTier(): Promise<string>;
    incrementApiCall(): Promise<void>;
    incrementVideoCount(): Promise<void>;
    resetHourlyApiCalls(): Promise<void>;
    searchWeb(searchQuery: string): Promise<Array<SearchResult>>;
    sendMessage(userMessage: string): Promise<string>;
    setGNewsKey(key: string): Promise<void>;
    setOpenRouterKey(key: string): Promise<void>;
    setTier(tierValue: string): Promise<boolean>;
    storeEvent(event: NewsEvent): Promise<void>;
    transformHttpResponse(raw: {
        context: Uint8Array;
        response: HttpResponse;
    }): Promise<HttpResponse>;
    triggerNewsRefresh(): Promise<{
        success: boolean;
        eventCount: bigint;
    }>;
}
import type { AgentState as _AgentState, AgentStatus as _AgentStatus, ChatMessage as _ChatMessage, MessageId as _MessageId, Role as _Role, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async checkQuota(): Promise<{
        allowed: boolean;
        limit: bigint;
        remaining: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.checkQuota();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkQuota();
            return result;
        }
    }
    async clearChat(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearChat();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearChat();
            return result;
        }
    }
    async dismissEvent(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.dismissEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dismissEvent(arg0);
            return result;
        }
    }
    async fetchNews(): Promise<Array<NewsArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchNews();
            return result;
        }
    }
    async getActiveAlerts(): Promise<Array<NewsEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveAlerts();
            return result;
        }
    }
    async getAgentState(): Promise<AgentState> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgentState();
                return from_candid_AgentState_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgentState();
            return from_candid_AgentState_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalytics(): Promise<AnalyticsSnapshot> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getChatHistory(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatHistory();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatHistory();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvents(): Promise<Array<NewsEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvents();
            return result;
        }
    }
    async getGNewsKey(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getGNewsKey();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGNewsKey();
            return result;
        }
    }
    async getLlmStatus(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getLlmStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLlmStatus();
            return result;
        }
    }
    async getNewsContextForChat(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsContextForChat();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsContextForChat();
            return result;
        }
    }
    async getOpenRouterKey(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenRouterKey();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenRouterKey();
            return result;
        }
    }
    async getRecentEvents(arg0: bigint): Promise<Array<NewsEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentEvents(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentEvents(arg0);
            return result;
        }
    }
    async getSystemInfo(): Promise<SystemInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemInfo();
            return result;
        }
    }
    async getTier(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getTier();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTier();
            return result;
        }
    }
    async incrementApiCall(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementApiCall();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementApiCall();
            return result;
        }
    }
    async incrementVideoCount(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementVideoCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementVideoCount();
            return result;
        }
    }
    async resetHourlyApiCalls(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetHourlyApiCalls();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetHourlyApiCalls();
            return result;
        }
    }
    async searchWeb(arg0: string): Promise<Array<SearchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchWeb(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchWeb(arg0);
            return result;
        }
    }
    async sendMessage(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0);
            return result;
        }
    }
    async setGNewsKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGNewsKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGNewsKey(arg0);
            return result;
        }
    }
    async setOpenRouterKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setOpenRouterKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOpenRouterKey(arg0);
            return result;
        }
    }
    async setTier(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setTier(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTier(arg0);
            return result;
        }
    }
    async storeEvent(arg0: NewsEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeEvent(arg0);
            return result;
        }
    }
    async transformHttpResponse(arg0: {
        context: Uint8Array;
        response: HttpResponse;
    }): Promise<HttpResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.transformHttpResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformHttpResponse(arg0);
            return result;
        }
    }
    async triggerNewsRefresh(): Promise<{
        success: boolean;
        eventCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.triggerNewsRefresh();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.triggerNewsRefresh();
            return result;
        }
    }
}
function from_candid_AgentState_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgentState): AgentState {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_AgentStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgentStatus): AgentStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_ChatMessage_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    newsAgent: _AgentStatus;
    lastEventCount: bigint;
    lastRunAt: bigint;
    mapAgent: _AgentStatus;
    videoAgent: _AgentStatus;
}): {
    newsAgent: AgentStatus;
    lastEventCount: bigint;
    lastRunAt: bigint;
    mapAgent: AgentStatus;
    videoAgent: AgentStatus;
} {
    return {
        newsAgent: from_candid_AgentStatus_n3(_uploadFile, _downloadFile, value.newsAgent),
        lastEventCount: value.lastEventCount,
        lastRunAt: value.lastRunAt,
        mapAgent: from_candid_AgentStatus_n3(_uploadFile, _downloadFile, value.mapAgent),
        videoAgent: from_candid_AgentStatus_n3(_uploadFile, _downloadFile, value.videoAgent)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MessageId;
    content: string;
    role: _Role;
    timestamp: _Timestamp;
}): {
    id: MessageId;
    content: string;
    role: Role;
    timestamp: Timestamp;
} {
    return {
        id: value.id,
        content: value.content,
        role: from_candid_Role_n8(_uploadFile, _downloadFile, value.role),
        timestamp: value.timestamp
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    idle: null;
} | {
    error: null;
} | {
    complete: null;
} | {
    running: null;
}): AgentStatus {
    return "idle" in value ? AgentStatus.idle : "error" in value ? AgentStatus.error : "complete" in value ? AgentStatus.complete : "running" in value ? AgentStatus.running : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    assistant: null;
}): Role {
    return "user" in value ? Role.user : "assistant" in value ? Role.assistant : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Array<ChatMessage> {
    return value.map((x)=>from_candid_ChatMessage_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
